export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_EXISTS = 'EMAIL_EXISTS',

  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  UNSUPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  INVALID_FILE_URL="INVALID_FILE_URL",
  DELETE_FILE_FAILED="DELETE_FILE_FAILED",
  FILE_NOT_FOUND="FILE_NOT_FOUND"
}
